### ISSUE TITLE
More-restrictive license?

### ISSUE THREAD

**Issue by capnslipp** [lmmenge/WatchSpringboard-Prototype#6]
Would it be possible to change the license for this project to something that requires derived works are required to be available free of charge (e.g. [GPL](http://choosealicense.com/licenses/gpl-3.0/) or [CC NonCommercial](https://creativecommons.org/licenses/))?

It feels dirty to have to pay someone else $4 for a jailbreak tweak that's largely your and the community's coding & design work, and ultimately a derivative of a full-copyright design (Apple's).  I'd love to contribute some of my own enhancements to your project (I took a stab at perspective-zoom wallpapers a while back that I still need to finish), but… you know… I'd like not to be forced to pay for my own work too.  The jailbreak community has a bad habit of taking others' hard work, slapping in a few hidden-method calls, and calling it their own creation.  Software licenses are pretty good at preventing that kind of behavior.

Thank you for your consideration.

---

_GitHub will no longer let me comment on this issue, so I'm adding it here:_

@lmmenge ¶1: If you say so.  The number of glitches & bugs in the currently-available tweaks hints that noit nearly as much work has been done by them as they'd like people to believe.

¶2: No, not at all.  And yes, initially it would have that effect.  But as this project progresses, I think their legacy fork would start looking antiquated enough for them to switch over; or someone new would re-do the integration work for the sake using the newer WatchSpringboard-Prototype codebase.

Your arguement is very similar to the arguments in the late 90s against open-source— people feared open-sourcing code because they thought they would lose control of their code, and others would be making profit off of repackaging the sourceror's work.  That has happened, as it is happening here— and the OSS community developed systems to ensure the creators are given fair credit, and derived works are free or licensed from the creators.

You're free to do what you want with your project, but history told and retold that loose open-source ends up with creatively-marketed clones, and tight open-source ends up with a strong, centralized community pushing forward together.

**Comment by lmmenge** [comment]
I think you greatly underestimate the work of the people in the community who developed tweaks based on this. People who worked to adapt this code to do enough to be warranted as a proper springboard replacement deserve every dollar paid to them. This project has incredibly little integration to be a springboard replacement.

Not to mention that it seems that you're under the impression that, if I changed the license of this project at this point in time, people who built upon this project would have to switch their licenses as well. That is not true, to my understanding. In fact, changing the license to something more "contagious" feels to me like it would do nothing but make people not want to use this code any longer.

Thanks for your suggestion, but it seems very unlikely that I'll change the license in this project to something that forbids commercial usage.

**Comment by iAlborz** [comment]
i think you sent this email to everyone who commented on that thing :)

**Comment by lmmenge** [comment]
@iAlborz what do you mean? Who else commented? I replied to https://github.com/lmmenge/WatchSpringboard-Prototype/issues/6 in my project. It seems to only have me, @capnslipp and now you.

**Comment by omnicons** [comment]
Anyone subscribed to it gets emailed.

**Comment by lmmenge** [comment]
@omnicons then I guess it's not my fault everyone got it. They're subscribed, after all (I'm not sure if at project-level or issue-level). I usually reply to issues created in my own project before closing them. Otherwise it wold just be plain rude of me :P

**Comment by omnicons** [comment]
I'm not complaining ^.^ Just being informative as to why we're getting
these. I've got the notifications turned off so it didn't bother me at all.
