### ISSUE TITLE
One item not centerented

### ISSUE THREAD

**Issue by ingouackaz** [lmmenge/WatchSpringboard-Prototype#8]
Hi ! @lmmenge  &

I am currently trying your lib and it's very awesome !

![ios simulator screen shot 2015-07-08 16 44 01](https://cloud.githubusercontent.com/assets/3285421/8573181/8c0192c0-2590-11e5-9f10-ded8ddcbf60b.png)

However, when i have less than 4 items, they are not properly centered :/
![ios simulator screen shot 2015-07-08 16 44 23]

(https://cloud.githubusercontent.com/assets/3285421/8573192/98f7f5d2-2590-11e5-9472-583fecf725b9.png)

Could you please help me to fix them ?

**Comment by lmmenge** [comment]
Thanks for the nice comments!
Unfortunately I'm no longer able to spend time on this project, but feel free to fork it and make your changes!
